issuer: http://127.0.0.1:5556
storage:
  type: kubernetes
connectors:
  - type: mock
    id: mock
    name: Mock

  - type: github
    id: github
    name: GitHub
    config:
      clientID: "$GITHUB_CLIENT_ID"
      clientSecret: "$GITHUB_CLIENT_SECRET"
      redirectURI: http://127.0.0.1:5556/callback/github
      org: kubernetes
web:
  http: 127.0.0.1:5556
